from .app_config import *

__all__=[
    # 应用程序基本信息
    APP_VERSION, 
    APP_NAME, 
    DEFAULT_WINDOW_TITLE,

    # 路径配置
    DESKTOP_ICO_PATH, RESOURCES_PATH, FILE_ICO_PATH,
    CONFIG_FILE, BUGS_REPORT_DIR, EMPTY_XLSX_TEMPLATE,

    # Windows API 常量
    SM_CXSCREEN, SM_CYSCREEN, GWL_EXSTYLE,
    WS_EX_TOOLWINDOW, WS_EX_APPWINDOW,

    # 动画和界面常量
    ANIMATION_STEPS, ANIMATION_DELAY, WINDOW_WIDTH_RATIO,
    WINDOW_HEIGHT_RATIO, WINDOW_POSITION_RATIO, TOLERANCE,
    CORNER_SIZE, WAIT_TIMEOUT, SLEEP_INTERVAL, MOUSE_CHECK_INTERVAL,

    # 文件类型配置
    SCRIPTS_TYPE, FILE_ICO,

    # 系统应用程序和命令配置
    SYSTEM_APPS, SYSTEM_COMMANDS, MIHOYO_GAMES,

    # 默认配置函数
    get_default_config

]

